return {
    'zaldih/themery.nvim',
    lazy = false,
    config = function()
        require('themery').setup {
            themes = {
                'retrobox',
                'randomhue',
                'quiet',
                'peachpuff',
                'pablo',
                'murphy',
                'morning',
                'minischeme',
                'minicyan',
                'lunaperche',
                'koehler',
                'kanagawa-wave',
                'kanagawa-lotus',
                'kanagawa-dragon',
                'kanagawa',
                'industry',
                'habamax',
                'gruvbox',
                'evening',
                'elflord',
                'desert',
                'delek',
                'default',
                'darkblue',
                'catppuccin-macchiato',
                'catppuccin-latte',
                'catppuccin-frappe',
                'blue',
                'ayu',
                'catppuccin-mocha',
                'zellner',
                'zaibatsu',
                'wildcharm',
                'vim',
                'unokai',
                'torte',
                'tokyonight-storm',
                'tokyonight-night',
                'tokyonight-moon',
                'tokyonight-day',
                'tokyonight',
                'sorbet',
                'slate',
                'shine',
                'ron',
                'nightfox',
                'dayfox',
                'dawnfox',
                'duskfox',
                'nordfox',
                'terafox',
                'carbonfox',
            },
            livePreview = true,
        }
    end,
}
